apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 2
  labels:
    app: canes-deployment
  name: canes-deployment
  namespace: canes
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: canes-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: canes-deployment
    spec:
      containers:
      - image: gcr.io/canes-268220/canes:28
        imagePullPolicy: Always
        name: canes
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
