CREATE DATABASE SUPLEMENTOS;

USE SUPLEMENTOS;
--
CREATE TABLE PRODUTO (
ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(150) NOT NULL,
DESCRICAO VARCHAR(1000) NOT NULL,
VALOR_UNIT NUMERIC(10,2) NOT NULL,
QUANTIDADE INT NOT NULL,
FK_ID_USUARIO INT NOT NULL,
STATUS VARCHAR(10) NOT NULL,
PRIMARY KEY (ID_PRODUTO)
);

CREATE TABLE OBJETIVO (
ID_OBJETIVO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
PRIMARY KEY (ID_OBJETIVO)
);

CREATE TABLE CATEGORIA (
ID_CATEGORIA INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
PRIMARY KEY (ID_CATEGORIA)
);

CREATE TABLE PROD_CATEGORIA (
ID INT NOT NULL AUTO_INCREMENT,
FK_ID_CATEGORIA INT,
FK_ID_PRODUTO INT,
PRIMARY KEY(ID),
FOREIGN KEY(FK_ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA),
FOREIGN KEY(FK_ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)
);

CREATE TABLE PROD_OBJETIVO (
ID INT NOT NULL AUTO_INCREMENT,
FK_ID_OBJETIVO INT,
FK_ID_PRODUTO INT,
PRIMARY KEY (ID),
FOREIGN KEY(FK_ID_OBJETIVO) REFERENCES OBJETIVO (ID_OBJETIVO),
FOREIGN KEY(FK_ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)
);

CREATE TABLE PROD_IMG (
ID_IMG INT NOT NULL AUTO_INCREMENT,
FK_ID_PRODUTO INT,
NOME VARCHAR(30) NOT NULL,
PRIMARY KEY (ID_IMG),
FOREIGN KEY(FK_ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)
);

INSERT INTO OBJETIVO (NOME)
VALUES ('Massa Magra'),
	   ('Emagrecimento'),
       ('Energia'),
       ('Saúde e Qualidade de vida'),
       ('Vitaminas');
       
INSERT INTO CATEGORIA (NOME)
VALUES ('Aminoácidos'),
	   ('Pré-treino'),
       ('Hipercalórico'),
       ('Proteínas'),
       ('Termogênicos');
       
CREATE TABLE PERGUNTA(
ID_PERGUNTA INT NOT NULL AUTO_INCREMENT,
PERGUNTA VARCHAR(100) NOT NULL,
PRIMARY KEY(ID_PERGUNTA)
);
       
CREATE TABLE RESPOSTA_PROD_PERG(
ID_RESPOSTA INT NOT NULL AUTO_INCREMENT,
RESPOSTA VARCHAR(100) NOT NULL,
FK_ID_PRODUTO INT NOT NULL,
FK_ID_PERGUNTA INT NOT NULL,
PRIMARY KEY(ID_RESPOSTA),
foreign key (FK_ID_PRODUTO) references PRODUTO (ID_PRODUTO),
FOREIGN KEY (FK_ID_PERGUNTA) references PERGUNTA(ID_PERGUNTA)
);     

INSERT INTO PERGUNTA (PERGUNTA)
VALUES ('O que é?'),   
       ('Para que serve?'),
       ('Como usar?'); 
	
CREATE TABLE FUNCIONARIO(
    ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(80) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    USUARIO VARCHAR(40) NOT NULL,
    SENHA VARCHAR(200) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    TIPO VARCHAR(14) NOT NULL,
    PRIMARY KEY(ID_FUNCIONARIO)
);

CREATE TABLE CLIENTE(
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
    NOME_CLIENTE VARCHAR(80) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    SENHA VARCHAR(200) NOT NULL,
    PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE ENDERECO_ENTREGA(
    ID_ENDERECO_ENT INT NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    RUA VARCHAR(100) NOT NULL,
    CEP VARCHAR (9) NOT NULL,
    NUMERO VARCHAR(6) NOT NULL,
    COMPLEMENTO VARCHAR(80),
    BAIRRO VARCHAR(60) NOT NULL,
    CIDADE VARCHAR(40) NOT NULL,
    ESTADO VARCHAR(40) NOT NULL,
    PRIMARY KEY(ID_ENDERECO_ENT),
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE ENDERECO_FATURAMENTO(
    ID_ENDERECO_FAT INT NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    RUA VARCHAR(100) NOT NULL,
    CEP VARCHAR (9) NOT NULL,
    NUMERO VARCHAR(6) NOT NULL,
    COMPLEMENTO VARCHAR(80),
    BAIRRO VARCHAR(60) NOT NULL,
    CIDADE VARCHAR(40) NOT NULL,
    ESTADO VARCHAR(40) NOT NULL,
    PRIMARY KEY(ID_ENDERECO_FAT), 
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE ITEM_PEDIDO(
    ID_ITEM_PEDIDO INT NOT NULL AUTO_INCREMENT,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALOR_UNITARIO NUMERIC(10,2) NOT NULL,
    VALOR_TOTAL NUMERIC(10,2) NOT NULL,
    NOME_PRODUTO VARCHAR(150) NOT NULL,
    ID_CLIENTE INT,
    PRIMARY KEY(ID_ITEM_PEDIDO)
);

CREATE TABLE PEDIDO(
    ID_PEDIDO INT NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    ID_ENTREGA INT NOT NULL,
    METODO_PAGAMENTO VARCHAR(150) NOT NULL,
    STATUS VARCHAR(150) NOT NULL,
    PRIMARY KEY(ID_PEDIDO),
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY(ID_ENTREGA) REFERENCES ENDERECO_ENTREGA(ID_ENDERECO_ENT)
);

CREATE TABLE ITEM_PEDIDO_VENDIDO(
    ID_ITEM_PEDIDO INT NOT NULL AUTO_INCREMENT,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALOR_UNITARIO NUMERIC(10,2) NOT NULL,
    VALOR_TOTAL NUMERIC(10,2) NOT NULL,
    NOME_PRODUTO VARCHAR(150) NOT NULL,
    ID_CLIENTE INT,
    ID_PEDIDO INT NOT NULL,
    PRIMARY KEY(ID_ITEM_PEDIDO),
    FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
);
